AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  SuggestExtensions: true

require: ['rubocop-rake', 'rubocop-minitest']

Rake:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertTruthy:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes # as God intended!
