AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  SuggestExtensions: false


Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes # as God intended!
